language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
env:
  matrix:
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=10.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=10.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=10.3"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=10.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=10.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=10.3"
    - TEST_OS="platform=iOS Simulator,name=iPhone 7,OS=10.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone SE,OS=10.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=10.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=10.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=10.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Pro,OS=10.3"

    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=10.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=10.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=10.2"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=10.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=10.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=10.2"
    - TEST_OS="platform=iOS Simulator,name=iPhone 7,OS=10.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone SE,OS=10.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=10.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=10.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=10.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Pro,OS=10.2"

    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=10.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=10.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=10.1"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=10.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=10.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=10.1"
    - TEST_OS="platform=iOS Simulator,name=iPhone 7,OS=10.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 7 Plus,OS=10.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone SE,OS=10.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=10.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=10.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=10.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Pro,OS=10.1"

    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=10.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=10.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=10.0"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=10.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=10.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=10.0"
    - TEST_OS="platform=iOS Simulator,name=iPhone 7,OS=10.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 7 Plus,OS=10.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone SE,OS=10.0"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=10.0"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=10.0"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=10.0"
    - TEST_OS="platform=iOS Simulator,name=iPad Pro,OS=10.0"

    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=9.3"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=9.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=9.3"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=9.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=9.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=9.3"
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=9.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=9.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=9.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=9.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Pro,OS=9.3"
    
    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=9.2"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=9.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=9.2"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=9.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=9.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=9.2"
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=9.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=9.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=9.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=9.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Pro,OS=9.2"

    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=9.1"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=9.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=9.1"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=9.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=9.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=9.1"
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=9.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=9.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=9.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=9.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Pro,OS=9.1"

    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=9.0"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=9.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=9.0"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s,OS=9.0"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6s Plus,OS=9.0"
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=9.0"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=9.0"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=9.0"
    - TEST_OS="platform=iOS Simulator,name=iPad Air 2,OS=9.0"

    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=8.4"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=8.4"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=8.4"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=8.4"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=8.4"    
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=8.4"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=8.4"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=8.4"

    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=8.3"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=8.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=8.3"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=8.3"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=8.3"    
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=8.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=8.3"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=8.3"

    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=8.2"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=8.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=8.2"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=8.2"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=8.2"    
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=8.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=8.2"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=8.2"

    - TEST_OS="platform=iOS Simulator,name=iPhone 4s,OS=8.1"
    - TEST_OS="platform=iOS Simulator,name=iPhone 5,OS=8.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 5s,OS=8.1"    
    - TEST_OS="platform=iOS Simulator,name=iPhone 6,OS=8.1"
    - TEST_OS="platform=iOS Simulator,name=iPhone 6 Plus,OS=8.1"    
    - TEST_OS="platform=iOS Simulator,name=iPad 2,OS=8.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Retina,OS=8.1"
    - TEST_OS="platform=iOS Simulator,name=iPad Air,OS=8.1"

xcode_project: Prey.xcodeproj
xcode_scheme: Prey
before_install:
    - gem install xcpretty -N --no-ri --no-rdoc
script: 
    - set -o pipefail
    - xcodebuild -project Prey.xcodeproj -scheme Prey clean test -destination "${TEST_OS}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty